"""Random name pools for NPC generation."""

FIRST_NAMES_M = [
    "Aaron", "Adam", "Alan", "Albert", "Alex", "Alfred", "Allen", "Alvin", "Andre", "Andrew",
    "Andy", "Anthony", "Antonio", "Arthur", "Austin", "Barry", "Benjamin", "Bernard", "Billy",
    "Bobby", "Brad", "Bradley", "Brandon", "Brent", "Brett", "Brian", "Bruce", "Bryan", "Calvin",
    "Carl", "Carlos", "Casey", "Charles", "Charlie", "Chester", "Chris", "Christian", "Christopher",
    "Clarence", "Claude", "Clayton", "Clifford", "Clinton", "Cody", "Colin", "Craig", "Curtis",
    "Dale", "Dan", "Daniel", "Danny", "Darrell", "Darren", "Dave", "David", "Dean", "Dennis",
    "Derek", "Derrick", "Don", "Donald", "Douglas", "Duane", "Dustin", "Dwayne", "Dylan",
    "Earl", "Eddie", "Edgar", "Edward", "Edwin", "Elijah", "Eric", "Ernest", "Ethan", "Eugene",
    "Evan", "Floyd", "Francis", "Frank", "Fred", "Frederick", "Gary", "Gene", "George", "Gerald",
    "Gilbert", "Glen", "Glenn", "Gordon", "Grant", "Greg", "Gregory", "Guy", "Harold", "Harry",
    "Harvey", "Henry", "Herbert", "Herman", "Howard", "Hugh", "Ian", "Isaac", "Ivan", "Jack",
    "Jacob", "Jake", "James", "Jason", "Jeff", "Jeffrey", "Jeremy", "Jerry", "Jesse", "Jimmy",
    "Joe", "Joel", "John", "Johnny", "Jonathan", "Jordan", "Jose", "Joseph", "Josh", "Joshua",
    "Juan", "Justin", "Keith", "Kenneth", "Kevin", "Kyle", "Larry", "Lawrence", "Lee", "Leon",
    "Leonard", "Lester", "Lewis", "Liam", "Lloyd", "Logan", "Louis", "Lucas", "Luke", "Marcus",
    "Mario", "Mark", "Martin", "Marvin", "Mason", "Matt", "Matthew", "Michael", "Mike", "Mitchell",
    "Nathan", "Neil", "Nicholas", "Noah", "Norman", "Oliver", "Oscar", "Patrick", "Paul", "Peter",
    "Philip", "Ralph", "Ramon", "Randy", "Raymond", "Richard", "Rick", "Robert", "Roger", "Ronald",
    "Roy", "Russell", "Ryan", "Samuel", "Scott", "Sean", "Seth", "Shane", "Shannon", "Shawn",
    "Spencer", "Stanley", "Stephen", "Steve", "Steven", "Terry", "Theodore", "Thomas", "Tim",
    "Timothy", "Todd", "Tom", "Tony", "Travis", "Trevor", "Troy", "Tyler", "Vernon", "Victor",
    "Vincent", "Walter", "Warren", "Wayne", "Wesley", "William", "Willie", "Zachary",
]

FIRST_NAMES_F = [
    "Abigail", "Alexandria", "Alice", "Alicia", "Alison", "Allison", "Amanda", "Amber", "Amy",
    "Andrea", "Angela", "Anita", "Ann", "Anna", "Anne", "Annette", "April", "Ashley", "Audrey",
    "Barbara", "Beth", "Bethany", "Betty", "Beverly", "Bonnie", "Brenda", "Brittany", "Brooke",
    "Carol", "Carole", "Caroline", "Carolyn", "Carrie", "Catherine", "Cathy", "Cheryl", "Christina",
    "Christine", "Cindy", "Claire", "Connie", "Crystal", "Cynthia", "Dana", "Deborah", "Debra",
    "Denise", "Diana", "Diane", "Donna", "Dorothy", "Eleanor", "Elizabeth", "Ellen", "Emily",
    "Emma", "Erica", "Erin", "Evelyn", "Faith", "Frances", "Gloria", "Grace", "Hannah", "Heather",
    "Helen", "Holly", "Jackie", "Jacqueline", "Janet", "Janice", "Jennifer", "Jessica", "Joan",
    "Joanna", "Joyce", "Judith", "Judy", "Julia", "Julie", "Karen", "Katherine", "Kathleen",
    "Kathy", "Katie", "Kay", "Kelly", "Kimberly", "Kristen", "Kristin", "Laura", "Lauren",
    "Leah", "Linda", "Lisa", "Lori", "Louise", "Lucy", "Lynn", "Margaret", "Maria", "Marie",
    "Marilyn", "Martha", "Mary", "Megan", "Melissa", "Michelle", "Monica", "Nancy", "Natalie",
    "Nicole", "Olivia", "Pamela", "Patricia", "Paula", "Peggy", "Rachel", "Rebecca", "Regina",
    "Renee", "Robin", "Rose", "Ruth", "Sandra", "Sara", "Sarah", "Sharon", "Sheila", "Shirley",
    "Stacy", "Stephanie", "Susan", "Tammy", "Teresa", "Tina", "Tiffany", "Tracy", "Valerie",
    "Victoria", "Virginia", "Wanda", "Wendy",
]

LAST_NAMES = [
    "Adams", "Alexander", "Allen", "Anderson", "Bailey", "Baker", "Barnes", "Bell", "Bennett",
    "Brooks", "Brown", "Bryant", "Butler", "Campbell", "Carter", "Clark", "Coleman", "Collins",
    "Cook", "Cooper", "Cox", "Cruz", "Davis", "Diaz", "Edwards", "Ellis", "Evans", "Fisher",
    "Flores", "Foster", "Garcia", "Gonzalez", "Gordon", "Graham", "Grant", "Gray", "Green",
    "Griffin", "Hall", "Hamilton", "Harris", "Harrison", "Hayes", "Henderson", "Hernandez",
    "Hill", "Howard", "Hughes", "Jackson", "James", "Jenkins", "Johnson", "Jones", "Kelly",
    "King", "Lee", "Lewis", "Long", "Lopez", "Martin", "Martinez", "Mason", "McDonald",
    "Mitchell", "Moore", "Morgan", "Morris", "Murphy", "Myers", "Nelson", "Nguyen", "Nichols",
    "Parker", "Patterson", "Perez", "Perry", "Peterson", "Phillips", "Pierce", "Price", "Ramirez",
    "Reed", "Rivera", "Roberts", "Robinson", "Rodriguez", "Rogers", "Ross", "Russell", "Sanchez",
    "Sanders", "Scott", "Simmons", "Smith", "Stewart", "Taylor", "Thomas", "Thompson", "Torres",
    "Turner", "Walker", "Ward", "Watson", "White", "Williams", "Wilson", "Wood", "Wright", "Young",
    "Abbott", "Aguilar", "Barker", "Barton", "Bishop", "Bowen", "Bowers", "Boyd", "Burke",
    "Burns", "Carr", "Carroll", "Castillo", "Castro", "Chavez", "Christensen", "Cole", "Curtis",
    "Davidson", "Duncan", "Ferguson", "Ford", "Freeman", "Fuller", "Gibson", "Glover", "Goodwin",
    "Gregory", "Hanson", "Hicks", "Holmes", "Hudson", "Hunter", "Jensen", "Johnston", "Joseph",
    "Knight", "Lawrence", "Lawson", "Mason", "Maxwell", "McCoy", "Medina", "Mendez", "Meyer",
    "Miles", "Mills", "Montgomery", "Moreno", "Murray", "Newman", "Norris", "Oliver", "Ortiz",
    "Owen", "Owens", "Palmer", "Patel", "Pearson", "Pena", "Porter", "Potter", "Powell",
    "Reyes", "Rhodes", "Rice", "Richardson", "Riley", "Robertson", "Ryan", "Shelton", "Simpson",
    "Sims", "Spencer", "Stanley", "Stephens", "Stevens", "Stone", "Sullivan", "Tran", "Tucker",
    "Vargas", "Vasquez", "Wade", "Wallace", "Warren", "Washington", "Watkins", "Weaver", "Webb",
    "Welch", "West", "Wheeler", "Williamson", "Willis", "Wolfe", "Woods",
]
